### ISSUE TITLE
confusing versioning strategy (`0.4.4` vs `0.5.0`)

### ISSUE THREAD

**Issue by mindrunner** [staratlasmeta/factory#127]
**Describe the bug**
It seems like the most recent release `0.5.0` does not contain some changes from `0.4.4`. The latest commits (including) the version bump went straight to `main` branch, which is still `16` commits behind `develop`.

**To Reproduce**
Use `getCreateExchangeTransaction`.  https://github.com/staratlasmeta/factory/pull/110 made the staking id optional. After upgrading to `0.5.0`, the method expects me to pass the id again (PR 110 never made it to `master).

```
  node_modules/@staratlas/factory/dist/marketplace/services/GmClientService.d.ts:121:138
    121     getCreateExchangeTransaction(connection: Connection, order: Order, orderTaker: PublicKey, purchaseQty: number, programId: PublicKey, stakingProgramId: PublicKey, registeredStake?: PublicKey): Promise<{
                                                                                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'stakingProgramId' was not provided.

```

**Expected behavior**
It would be nice to have a proper verisoning / release path.

Maybe this was intentional, but it does not really look like it.

**Comment by Buzzec** [comment]
`0.5.0` should have just been an update to the `getTokenAccount` function that was a breaking api change so required a minor bump. I'm going to look into what changed and we'll do a `0.5.1` release once we've resolved it.

**Comment by Buzzec** [comment]
`0.4.4` is still compatible, there were no on-chain changes in `0.5.0` so should work until we resolve this release issue.

**Comment by mindrunner** [comment]
Yea, not a blocker. just confusion :) Thanks for looking at it.

**Comment by Buzzec** [comment]
`0.5.1` released
