### ISSUE TITLE
GmEventService is not a constructor | Getting all open orders for multiple assets at once

### ISSUE THREAD

**Issue by skullnbonesdao** [staratlasmeta/factory#85]
## Problem
Get all open orders for assets at once.
Cause running `getOpenOrdersForAssets` in a loop causes to many request and my current solution is using a rate-limit.

## Solution
```ts
getOpenOrdersForAssets(connection: Connection, assetMint: PublicKey[], programId: PublicKey): Promise<[OrderAccountItemAsset])[]>
```
where
```ts
export interface OrderAccountItemAsset {
  assetMint: PublicKey;
  orders: OrderAccountItem[];
}
```
#### Alternatives Considered
rate limiting? 

## Notes
If there is already a way please let me know.
Thanks S&B

**Comment by skullnbonesdao** [comment]
....[update] 

So I found the GmOrderbookService class by now which should do exactly what i want. 

But trying to implement it gives me the following error:

```
Uncaught (in promise) TypeError: anchor_1.Wallet is not a function
    GmEventService GmEventService.ts:48
    GmOrderbookService GmOrderbookService.ts:46
```
![error_gmOrderBookService](https://user-images.githubusercontent.com/99446784/181103654-d28f1654-0c01-4b87-9a0d-bc3a08e53fd1.png)

**Comment by Mithium** [comment]
I can confirm I have the same exact error with GmOrderbookService

**Comment by MikeLuDev** [comment]
Hi @skullnbonesdao @redspatula - we're taking a look into this. Thanks for the report!

**Comment by MikeLuDev** [comment]
Quick update on this is that it appears that this issue is specific to the browser environment. Running the service inside of a Node.js server, for example, with the same code linked above works just fine.

Obviously this is a client side package though so we should expect it to work properly in the browser, so we'll keep digging :+1:

**Comment by skullnbonesdao** [comment]
Don't really know if this is the exact issue here but it seems like its related (since a import gets converted into a require when running `npm build` ) maybe this helps:

- https://stackoverflow.com/questions/43815928/why-does-this-npm-package-say-it-is-not-a-constructor
- https://stackoverflow.com/questions/42475691/importing-vs-requiring-with-babel-in-node/42475844#42475844

There seems to be also a update in the `anchor` package since there is an issue with that exact import/require statement:
```json
"@project-serum/anchor": "^0.24.2" => 0.25.0
```

Hope this helps :pray:

**Comment by redspatula** [comment]
Thanks for the update. I no longer have that bug. Site is up and running now again =D

**Comment by MikeLuDev** [comment]
Awesome, thanks for the confirmation @redspatula. Closing this issue as completed for now but feel free to re-flag if anyone else is still experiencing it.
