### ISSUE TITLE
Orderbook (getter) contains unfillable orders

### ISSUE THREAD

**Issue by skullnbonesdao** [staratlasmeta/factory#97]
**Describe the bug**
Orders not the same as in 'play.staratlas.com/market/'

**To Reproduce**
Fetch the Orderbook using 
```js
new GmClientService().getAllOpenOrders(...)
```

**Expected behavior**
A list of all assets in the GM which should be contain the same Orders as shown in the GM/'play.staratlas.com/market/'.

The issue here is that some orders that ```getAllOpenOrders(...)``` returns are not listed in the GM. 

Example:
Fimbul Airbike (sell)
| GM | factory | info | 
| --- | --- | -- |
| - | [2.8, 1, 5F28...Jqyd] | missing in GM |
| [4.1797, 1, 6uJJ...mTkS] |  [4.1797, 1, 6uJJ...mTkS] | ok |
| [...] | [...] | 

**Additional context**
Is that due to the reasons those Orders can not be filled? 
Did StarAtlas added a 'blacklist' for those Accounts/Orders? How are we supposed to filter out those 'malicious' Orders?

Thanks for any help on this.

**Comment by skullnbonesdao** [comment]
since the latest update we seem to get the same data as the SA-GM so i will close this issue for now!

**Comment by skullnbonesdao** [comment]
the issue is not solved just in the other direction we see high sells now!

![orders](https://user-images.githubusercontent.com/99446784/188932076-57f87c59-e700-4f5a-9bc9-c115154b737e.png)

**Comment by emberist** [comment]
Any update on this issue?

**Comment by skullnbonesdao** [comment]
for now this seems to be fixed by the team
